### ISSUE TITLE
Prioriter listen af deltagere i instruktør feltet

### ISSUE THREAD

**Issue by tv2-pvin** [anthiras/crimsonweb#12]
Når man laver et hold og skal vælge instruktøre, leder navnvælgeren i listen af alle dansere. 
Det kunne være rart at have en prioriteret liste så alle instruktører står øvers i den liste i den visning og så derefter er alfabestisk sorteret.

**Comment by anthiras** [comment]
Jeg har lavet noget lignende nu. Den nemmeste løsning var at vise instruktører som default options inden man begynder at taste.
