### ISSUE TITLE
Repræsenter holdene som en kalender-ish visning

### ISSUE THREAD

**Issue by tv2-pvin** [anthiras/crimsonweb#3]
Det er ønsket at kunne vise holdene i et kalender-baseret view for at øge oversigtbarheden når der er mange hold i gang eller kommende.

kalenderen behøver ikke at have en fuld 24 timers dag langs tidsaksen, men vise holdene på de dage de pågår i kronologisk rækkefølge.

**Comment by anthiras** [comment]
Jeg tænker vi skal starte med at finde på et godt design. Måske kan vi finde inspiration fra andre event/holdlister. Jeg har kigget på Nic's blokoversigter som giver et godt overblik men fylder lidt rigeligt horisontalt på mobilen.

**Comment by anthiras** [comment]
Måske noget i den her stil. Dog duer det ikke med enkelt-events/workshops, dem skal vi nok flytte til et andet view.

![Screenshot from 2022-10-16 21-09-18](https://user-images.githubusercontent.com/35039086/196053479-80b65b06-19bb-4787-b5f7-553807848f28.png)

**Comment by tv2-pvin** [comment]
Det ser godt ud, er den feedback jeg får.

Et ønske var at når man scroller ned (hvis den ikke allerede gør det) at ugenumrene pinner til toppen og følger med nedad
