### ISSUE TITLE
Muligheden for at angive et brugernavn

### ISSUE THREAD

**Issue by tv2-pvin** [anthiras/crimsonweb#5]
Vi ville gerne at man som bruger kunne tilknytte et navn til den email man tilmelder sig med.

Det navn skulle så brgues hvis tilgeængeligt i hold visninger osv.

Dette vil lette brugen at systemet for instruktørerne i den daglige brug.

**Comment by anthiras** [comment]
Det er der da allerede?

**Comment by tv2-pvin** [comment]
Det er der da også, bekalger jeg har sovet i timen der :)
