### ISSUE TITLE
Students need to be able to sign off a class themselves after they have been accepted.

### ISSUE THREAD

**Issue by tv2-pvin** [anthiras/crimsonweb#8]
Det er ikke muligt for folk selv at afmelde sig et hold de har tilmeldt sig når de først er godkendt.

Det vil vi gerne give dem muligheden for.

**Comment by anthiras** [comment]
Ok, I skal så bare være opmærksomme på at kønsfordelingsalgoritmen ikke vil kunne garantere korrekt fordeling hvis folk afmelder sig.

**Comment by tv2-pvin** [comment]
Ja det er allerede tilfældet når vi gør det for folk p.t.

**Comment by anthiras** [comment]
Done.
